version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5436:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app-instance1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_USER: postgres
      DB_PASSWORD: mypassword
      USER: user1
    ports:
      - "8081:8080"
    volumes:
      - /tmp:/tmp
    depends_on:
      - postgres

  app-instance2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_USER: postgres
      DB_PASSWORD: mypassword
      USER: user2
    ports:
      - "8082:8080"
    volumes:
      - /tmp:/tmp
    depends_on:
      - postgres

volumes:
  postgres-data:
