spring:
  application:
    name: filesystem-handler
  datasource:
    url: jdbc:postgresql://postgres:5436/postgres
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true